# Generated by Django 3.0.11 on 2021-04-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_stripe_cistomer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_cistomer_id',
            new_name='stripe_customer_id',
        ),
    ]
