# Generated by Django 3.0.11 on 2021-04-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210422_2203'),
        ('users', '0004_user_stripe_customer_id'),
    ]

    operations = [
    ]
