# Generated by Django 3.0.11 on 2021-04-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20210422_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_cust_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
